apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-kubelet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtual-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - patch
      - create
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
      - slurm.sylabs.io
    resources:
      - slurmjobs
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet
subjects:
  - kind: ServiceAccount
    name: virtual-kubelet
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtual-kubelet
---
apiVersion: v1
kind: Pod
metadata:
  name: vkubelet-slurm-0
spec:
  serviceAccountName: virtual-kubelet
  containers:
    - name: vkubelet-slurm-0
      image: cali4888/vk:0.0.1
      imagePullPolicy: Always
      args:
        - --nodename
        - vkubelet-slurm-0
        - --provider
        - slurm
        - --startup-timeout
        - 10s
      volumeMounts:
        - name: syslurm-mount
          mountPath: /syslurm
        - name: kubelet-crt
          mountPath: /kubelet.crt
        - name: kubelet-key
          mountPath: /kubelet.key
      env:
        - name: VK_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VK_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VKUBELET_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PARTITION
          value: "debug"
        - name: RED_BOX_SOCK
          value: "/syslurm/red-box.sock"
        - name: APISERVER_CERT_LOCATION
          value: "/kubelet.crt"
        - name: APISERVER_KEY_LOCATION
          value: "/kubelet.key"
      ports:
        - name: metrics
          containerPort: 10255
      readinessProbe:
        httpGet:
          path: /stats/summary
          port: metrics
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  volumes:
    - name: syslurm-mount
      hostPath:
        path: /var/run/syslurm
        type: Directory
    - name: kubelet-crt
      hostPath:
        path: /var/lib/kubelet/pki/kubelet.crt
        type: File
    - name: kubelet-key
      hostPath:
        path: /var/lib/kubelet/pki/kubelet.key
        type: File
